### PR TITLE
fix(core): proxy-loader behavior is not correct when query is string

### LINKED ISSUE #155: [Bug]: Looking for loader by default
### Version

```sh
System:
    OS: macOS 14.1.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 297.38 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Brave Browser: 120.1.61.120
    Chrome: 119.0.6045.105
    Firefox: 120.0
    Firefox Developer Edition: 118.0
    Safari: 17.1.2
  npmPackages:
    @rsdoctor/rspack-plugin: ^0.1.0 => 0.1.0
```

### Details

I tried to follow the [Quick Start](https://rsdoctor.dev/guide/start/quick-start) guide on my rsbuild react project.
But when I try to run `RSBUILD=true rsbuild build`, it keeps outputting error like this:

```bash
info    Ts checker running...
info    Ts checker is running slowly and will block builds until it is complete, please be patient and wait.
error   Failed to build.
error   TypeError: Cannot read properties of undefined (reading 'startsWith')
    at /projects/react-chakra-rsbuild/node_modules/.pnpm/@rspack+core@0.5.0_@swc+helpers@0.5.3/node_modules/@rspack/core/dist/config/adapterRuleUse.js:48:24
```

I try to see adapterRuleUse.js and it looks for `loader`
Then I try to read further on the rsdoctor configuration documentation and found [this section](https://rsdoctor.dev/config/options/index#features)

After adding this configuration:
```ts
// rsbuild.config.ts
export default defineConfig({
  ...
  tools: {
    // https://rsbuild.dev/config/plugins#rspack-plugins
    rspack: {
      plugins: [
        ...,
        new RsdoctorRspackPlugin({
          features: {
             loader: false,
          },
        }),
      ].filter(Boolean),
    },
  },
});
```

It work correctly.

I believe this could be improved by:
- [Alt 01] telling the audience to set the loader to false if there's no loader being used in Quick Start guide.
- [Alt 02] make it false by default

Correct me if this is intentional, as I believe other people who use rsbuild and want to try rsdoctor might encounter this issue and having hard time what to do.

### Reproduce link

https://github.com/sozonome/rsbuild-react-chakra-starter/blob/main/rsbuild.config.ts#L26

### Reproduce Steps

1. Follow Quick Start guide
2. Configure rsbuild.config.ts to use RsdoctorRspackPlugin
3. run `RSBUILD=true rsbuild build`

### PR DESCRIPTION
**Pull request by SoonIter**
## Summary

There are some problems in the implementation of two places.

1. in loader `this.query` hits `this.resourceQuery`

2. when `rule.use` is a function, rsdoctor cannot handle correctly

## Related Links

closes #155

## Checklist

- [x] I have added changeset via `pnpm run change`.
- [ ] I have updated the documentation.
- [x] I have added tests to cover my changes.

### CODE REVIEW

File: packages/core/src/build-utils/build/utils/loader.ts [hunk 1]
```diff
@@ -190,7 +241,10 @@ export function createLoaderContextTrap(
               if (options.hasOptions) {
                 return omit(target.query, [Loader.LoaderInternalPropertyName]);
               }
-              return target.resourceQuery;
+              const postfixRE = /[#?].*$/s;
+              const resource = options?.loader;
+              const loaderQuery = (postfixRE.exec(resource) ?? '').toString();
```
Comment (SoonIter) [inline packages/core/src/build-utils/build/utils/loader.ts:246]: We are unable to handle situations where folders contain a question mark (?). We need to confirm whether webpack and rspack can handle this.

Comment (SoonIter) [reply packages/core/src/build-utils/build/utils/loader.ts:246]: https://github.com/vitejs/vite/issues/15726

Comment (SoonIter) [reply packages/core/src/build-utils/build/utils/loader.ts]: webpack https://github.com/webpack/webpack/blob/2953d23a87d89b3bd07cf73336ee34731196c62e/lib/util/identifier.js#L311
rspack https://github.com/web-infra-dev/rspack/blob/d22f049d4bce4f8ac20c1cbabeab3706eddaecc1/packages/rspack/src/loader-runner/index.ts#L47

Neither "webpack" nor "vite" nor "rspack" handle situations where folders contain a "?"

File: packages/core/src/build-utils/build/utils/loader.ts [hunk 2]
```diff
@@ -5,18 +5,37 @@ import { Loader } from '@rsdoctor/utils/common';
...
+    path: match?.[1].replace(/\0(.)/g, '$1') || '',
+    query: match?.[2] ? match[2].replace(/\0(.)/g, '$1') : '',
+    fragment: match?.[3] || '',
+  };
+}
+
 export function loadLoaderModule(
-  p: string,
-  cwd = process.cwd(),
+  loaderPath: string,
```
Comment (easy1090) [inline packages/core/src/build-utils/build/utils/loader.ts:27]: if cwd need default value ? like: process.cwd()

**Comment by SoonIter** [comment]
image

image

**Review by easy1090 — APPROVED** [review]

**Comment by SoonIter** [comment]
thanks :D
